FES.AusleihSystem/FES.AusleihSystem/Controllers/AusleihController.cs
using FES.AusleihSystem.Data;
using FES.AusleihSystem.Models;
using FES.AusleihSystem.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FES.AusleihSystem.Controllers
{
    public class AusleihController : Controller
    {
        /// <summary>
        /// Dieser Controller welcher die Ausleih und Reserverierungen händelt
        /// </summary>
        private readonly ApplicationDbContext _context;
        private UserManager<ApplicationUser> _user;

        /// <summary>
        /// Der Konstruktor wird zur Laufzeit aufgerufen, sobald der User auf .../Ausleih/... gelangt 
        /// </summary>
        /// <param name="context">Bekommt vom Service den aktuellen DbContext</param>
        /// <param name="user">Bekommt vom Service den aktuellen User</param>
        public AusleihController(ApplicationDbContext context, UserManager<ApplicationUser> user)
        {
            _context = context;
            _user = user;
        }

        /// <summary>
        /// Zeigt einfach nur eine View mit allen Reservierungen an
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Ubersicht(string errormsg = null)
        {
            List<ReservierungViewModel> res = new List<ReservierungViewModel>();
            GeraetViewModel ger = new GeraetViewModel();
            IQueryable<GeraetViewModel> gerList;
            var userID = _user.GetUserId(User);
            var userRole = await _user.IsInRoleAsync(await _user.GetUserAsync(User), "Admin");

            foreach (var reservierung in _context.Reservierungen)
            {
                if (userRole || reservierung.NutzerID == userID)
                {
                    var posible = _context.Geraete.Where(g => g.Reservierung != null);
                    gerList = posible.Where(g => g.Reservierung.ReservierungsNummer == reservierung.ReservierungsNummer);/*ctx.Geraete.Where(g => g.Reservierung.ReservierungsNummer == reservierung.ReservierungsNummer);*/
                    reservierung.GeraeteListe = gerList.ToList();
                    res.Add(reservierung);
                }

            }

            return View(res);
        }

        [HttpGet]
        [Authorize]
        public IActionResult ReservierungAnlegen()
        {
            //List<GeraeteKategorie> kat = new List<GeraeteKategorie>();
            //kat = _context.Kategorien.ToList();
            //ViewBag.kategorien = kat;

            GeraeteReservierungModel model = new GeraeteReservierungModel();
            model.KategorieList = _context.Kategorien.ToList();
            //            model.ReservierungsDauer = model.ReservierungsEnde - model.ReservierungsBeginn;
            model.ReservierungsBeginn = DateTime.Now;
            model.ReservierungsEnde = DateTime.Now;
            model.ReservierungsBeginnZeit = DateTime.Now;
            model.ReservierungsEndeZeit = DateTime.Now.AddMinutes(45.0);
            return View(model);
        }

        /// <summary>
        /// Prüft ob das eingegebene Model Valide ist und legt anschließend eine Reservierung an
        /// </summary>
        /// <param name="model">Nutzer Eingeben bei /Ausleih/ReservierungAnlegen</param>
        /// <returns></returns>
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> ReservierungAnlegen(GeraeteReservierungModel model)
        {
            if (ModelState.IsValid)
            {
                var nutzer = await _user.GetUserAsync(User);
                var VM = new ReservierungViewModel()
                {

                    NutzerID = nutzer.Id,
                    GeraeteListe = GetGeraet(model.GeraeteEan),
                    ReservierungsBeginn = model.ReservierungsBeginn.Date + model.ReservierungsBeginnZeit.TimeOfDay,
                    ReservierungsEnde = model.ReservierungsEnde.Date + model.ReservierungsEndeZeit.TimeOfDay,
                    ReservierungsDauerTage = model.ReservierungsEnde.Date - model.ReservierungsBeginn.Date,
                    ReservierungsDauerStunden = model.ReservierungsEndeZeit - model.ReservierungsBeginnZeit,
                    ReservierungsZeitpunkt = DateTime.Now
                };



                _context.Reservierungen.Add(VM);
                _context.SaveChanges();


                return RedirectToAction("Ubersicht");
            }
            return View();
        }

        /// <summary>
        /// Nur Admins dürfen Löschen
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        //[Authorize(Roles = "Admin")]
        public IActionResult Loeschen(ReservierungViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.ReservierungsNummer == 0)
                {
                    Console.WriteLine("Kein Model gefunden");
                }
                else
                {
                    var res = _context.Reservierungen.First(g => g.ReservierungsNummer == model.ReservierungsNummer);
                    var geraete = _context.Geraete.Where(g => g.Reservierung.ReservierungsNummer == res.ReservierungsNummer);
                    foreach (var gerat in geraete)
                    {
                        //_context.Geraete.Remove(gerat);
                        gerat.GeraeteStatus = GeraetViewModel.Status.isVerfugbar;
                        gerat.Reservierung = null;
                        //_context.Geraete.Update(g => g.ID == gerat.ID);
                        //_context.Reservierungen.Remove(res);
                        // _context.Geraete.Add(gerat);
                        _context.Geraete.Update(gerat);

                    }

                    _context.Reservierungen.Remove(res);
                    _context.SaveChanges();
                }

                return RedirectToAction("Ubersicht");
            }
            return RedirectToAction("Ubersicht");
        }
        [Authorize(Roles = "Admin")]
        public IActionResult IstReserviert(ReservierungViewModel model)
        {
            if (ModelState.IsValid)
            {
                var res = _context.Reservierungen.Where(r => r.ReservierungsNummer == model.ReservierungsNummer).FirstOrDefault();
                res.AusgeliehenStatus = ReservierungViewModel.EntliehenStatus.isAusgeliehen;
                _context.Reservierungen.Update(res);
                _context.SaveChanges();
                return RedirectToAction("Ubersicht");
            }
            return RedirectToAction("Ubersicht");
        }


        private GeraetViewModel GetGeraetByKategorie(GeraeteKategorie kat)
        {
            var cont = _context.Geraete.Where(g => (g.GeKategorie.Name == kat.Name && g.GeraeteStatus == GeraetViewModel.Status.isVerfugbar));
            return cont.FirstOrDefault();
        }
        private List<GeraetViewModel> GetGeraet(int id)
        {
            var result = new List<GeraetViewModel>();
            IQueryable<GeraetViewModel> temp;


            temp = _context.Geraete.Where(g => (g.EAN == id && g.GeraeteStatus == GeraetViewModel.Status.isVerfugbar));
            if (temp.Count() > 0)
            {
                foreach (var geraet in temp)
                {
                    result.Add(geraet);
                    geraet.GeraeteStatus = GeraetViewModel.Status.isReserviert;
                }
            }

            return result;
        }
        //public IActionResult GerateTabelleReload(GeraeteReservierungModel model)
        //{
        //    var gerateList = _context.Geraete.Where(g => g.Kategorie == model.Kategorie.Name);
        //    model.GerateTabelle.CleanList();

        //    foreach (var item in gerateList)
        //    {
        //        model.GerateTabelle.AddGeraet(item);
        //    }
        //    return RedirectToAction("Ubersicht");
        //}
        public IActionResult GerateTabelleReload(int id)
        {
            return RedirectToAction("Ubersicht");
        }
        public JsonResult GerateTabelleReloadJson(int id)
        {
            var result = Json(_context.Geraete.Where(g => g.GeKategorie.ID == id && g.GeraeteStatus == GeraetViewModel.Status.isVerfugbar).OrderBy(o => o.ID).ToList());
            return result;
        }
        public List<GeraetViewModel> GetGeraete()
        {
            return _context.Geraete.ToList();
        }
    }
}

FES.AusleihSystem/FES.AusleihSystem/Controllers/SeedingDataController.cs
using FES.AusleihSystem.Data;
using FES.AusleihSystem.Models;
using FES.AusleihSystem.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FES.AusleihSystem.Controllers
{
    public class SeedingDataController : Controller
    {
        /// <summary>
        /// Fügt Geräte und Rollen hinzu
        /// Testdaten
        /// </summary>
        private string[] GeraeteNamen = new string[]
        {
            "Beamer",
            "Laptop",
            "PC",
            "Monitor",
            "Lautsprecher",
            "Maus",
            "Tastatur",
            "HDMI-Kabel"
        };

        public static string[] Roles = new string[]
        {
            "Admin",
            "Lehrer",
            "Schueler"

        };
        public static string[] Kategorien = new string[]
        {
            "Beamer",
            "Laptop",
            "PC",
            "Sonstiges"
        };

        private enum Zuordnung
        {
            Beamer=1,
            Laptop=2,
            PC=3,
            Monitor=4,
            Lautsprecher=4,
            Maus=4,
            Tastatur=4,
            HDMI=4

        }

        private Gerate[] Namen = new Gerate[]
        {
            new Gerate(){Name="Lenovo", Kategorie="Laptop"},
            new Gerate(){Name="Dell", Kategorie="Laptop"},
            new Gerate(){Name="HP", Kategorie="PC"},
            new Gerate(){Name="HP", Kategorie="Sonstiges"},
            new Gerate(){Name="Epson", Kategorie="Beamer"},
            new Gerate(){Name="Medion", Kategorie="PC"},
            new Gerate(){Name="Acer", Kategorie="Beamer"},
            new Gerate(){Name="Acer", Kategorie="Laptop"},
            new Gerate(){Name="Corsair", Kategorie="Sonstiges"},

        };

        //public void SeedGeraeteData()
        //{
        //    var ran = new Random();

        //    for (int i = 0; i < 100; i++)
        //    {
        //        var ger = Namen[ran.Next(0,6)];
        //        _context.Geraete.Add(ger);
        //    }

        //    //_context.Geraete.Add
        //}

        private ApplicationDbContext _context;
        private IServiceProvider _service;
        private int SeedSize = 100;
        public SeedingDataController(ApplicationDbContext context, IServiceProvider service)
        {
            _context = context;
            _service = service;
        }

        public IActionResult Seeding()
        {
            SeedGeraeteData();
            return RedirectToAction("Index", "Home");
        }
        public async void SeedRollen()
        {
            IServiceScopeFactory scopeFactory = _service.GetRequiredService<IServiceScopeFactory>();
            using (IServiceScope scope = scopeFactory.CreateScope())
            {
                RoleManager<IdentityRole> roleManager = scope.ServiceProvider.GetRequiredService<RoleManager<IdentityRole>>();

                foreach (var role in Roles)
                {
                    if (await roleManager.FindByNameAsync(role) == null)
                    {
                        await roleManager.CreateAsync(new IdentityRole { Name = role });
                    }
                }
            }
        }
        public void KategorieSeeding()
        {
            for (int i = 0; i < Kategorien.Length; i++)
            {
                var Kategorie = new GeraeteKategorie
                {
                    Name = Kategorien[i]
                };
                Console.Write(Kategorien[i] + "wurde hinzugefügt, ");
                _context.Kategorien.Add(Kategorie);
            }
            _context.SaveChanges();
            Console.WriteLine("Kategorien wurden geseedet");

        }
        public void SeedGeraeteData()
        {
            Random ran;
            int name;
            int ean;
            KategorieSeeding();
            ran = new Random();

            //Geräte Seeding
            for (int i = 0; i < SeedSize; i++)
            {
                name = ran.Next(0, 9);
                var catint = ran.Next(1, 4);
                ean = ran.Next(10000000, 99999999);
                var mod = Namen[name];
                var gerat = new GeraetViewModel()
                {

                    Name = mod.Name,
                    GeraeteStatus = GeraetViewModel.Status.isVerfugbar,
                    Kategorie = _context.Kategorien.Where((o) => o.Name == mod.Kategorie).FirstOrDefault().Name,
                    GeKategorie = _context.Kategorien.Where((o) => o.Name == mod.Kategorie).FirstOrDefault(),
                    EAN = ean,
                };
                _context.Geraete.Add(gerat);
            }
            _context.SaveChanges();

            if (_context.UserRoles.Count() < 1)
            {
                SeedRollen();
                Console.WriteLine("Rollen wurden geseedet");
            }
            if (_context.Kategorien.Count() < 1)
            {

            }

        }
        //public void AddKatToGeraet()
        //{
        //    var ger = _context.Geraete.Where((o) => o.GeKategorie == null || o.Kategorie == null);
        //    var rand = new Random();

        //    foreach (var item in ger.ToList())
        //    {
        //        var i = rand.Next(1, 3);
        //        var gerat = _context.Geraete.Where((o) => o.ID == item.ID).FirstOrDefault();
        //        gerat.Kategorie = _context.Kategorien.Where((o) => o.ID == i).FirstOrDefault().Name;
        //        gerat.GeKategorie = _context.Kategorien.Where((o) => o.ID == i).FirstOrDefault();
        //        _context.Geraete.Remove(item);
        //        _context.Geraete.Add(gerat);
        //    }
        //    _context.SaveChangesAsync();
        //}

        public class Gerate
        {
            public string Name { get; set; }
            public string Kategorie { get; set; }
           public int Ean { get; set; }
        }
    }
}

FES.AusleihSystem/FES.AusleihSystem/Views/Shared/_Layout.cshtml


@using Microsoft.AspNetCore.Identity
@using FES.AusleihSystem.Models;
@using FES.AusleihSystem.ViewModels;

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                   
                </button>
                @*<a asp-area="" asp-controller="Account" asp-action="Profil" class="navbar-brand">FES.AusleihSystem</a>*@
                <img src="~/images/Icon.png" height="50" />
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    
                    @*<li><a asp-area="" asp-controller="Hardware" asp-action="GeraeteAnsicht">Geräte Anzeigen</a></li>
                    <li><a asp-area="" asp-controller="Hardware" asp-action="AddGeraet">Gerät hinzufügen</a></li>
                    <li><a asp-area="" asp-controller="Ausleih" asp-action="Ubersicht">AusleihUbersicht</a></li>
                    <li><a asp-area="" asp-controller="Ausleih" asp-action="ReservierungAnlegen">Reservieren</a></li>
                    <li><a asp-area="" asp-controller="SeedingData" asp-action="Seeding">Datenbank füllen</a></li>*@
                </ul>
                @await Html.PartialAsync("_LayoutPartial");
            </div>
        </div>
    </nav>
    <div class="container body-content" >
        @RenderBody()
        <hr />
        <footer>

            <p>&copy; 2017 - ProFESion</p>
        </footer>
    </div>

    <environment names="Staging,Production">

        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>



    @RenderSection("Scripts", required: false)
</body>
</html>


FES.AusleihSystem/FES.AusleihSystem/Views/Shared/_LayoutPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using FES.AusleihSystem.Controllers;
@using FES.AusleihSystem;


@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@if (SignInManager.IsSignedIn(User))
{
    <form asp-area="" asp-controller="Account" asp-action="Logout" method="post">
        <ul class="nav navbar-nav">

            @if (User.IsInRole("Admin"))
            {
                <li><a asp-area="" asp-controller="Hardware" asp-action="AddGeraet">Gerät hinzufügen</a></li>
            }

            <li><a asp-area="" asp-controller="Hardware" asp-action="GeraeteAnsicht">Geräteanzeige</a></li>
            <li><a asp-area="" asp-controller="Ausleih" asp-action="Ubersicht">Reservierungen</a></li>
            <li><a asp-area="" asp-controller="Ausleih" asp-action="ReservierungAnlegen">Reservieren</a></li>


        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li>
                <a asp-controller="Account" asp-action="Profil">@UserManager.GetUserName(User)</a>
            </li>
            <li>
                <button type="submit" class="btn btn-link navbar-btn navbar-link">Log out</button>
            </li>
        </ul>
    </form>
}
else
{
    <ul class="nav navbar-nav navbar-right">
        <li><a asp-area="" asp-controller="Account" asp-action="Register">Registrieren</a></li>
        <li><a asp-area="" asp-controller="Account" asp-action="Login">Login</a></li>
    </ul>
}